name: Test jpackage

on:
  pull_request:
    branches: [ main ]

jobs:
  test-jpackage:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          
      - name: Build JAR
        run: mvn -B package
        
      - name: Test jpackage
        shell: bash
        run: |
          jpackage --input target \
                   --main-jar mvn2llm.jar \
                   --name mvn2llm-test \
                   --type app-image \
                   --java-options "--enable-preview --enable-native-access=ALL-UNNAMED" \
                   --dest target/jpackage-test \
                   || (echo "jpackage failed, trying without app-version" && \
                       jpackage --input target \
                                --main-jar mvn2llm.jar \
                                --name mvn2llm-test \
                                --type app-image \
                                --java-options "--enable-preview --enable-native-access=ALL-UNNAMED" \
                                --dest target/jpackage-test)
                   
      - name: List output
        shell: bash
        run: ls -la target/jpackage-test/