name: Build Native Image on Linux

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number for the build (e.g., 1.0.0)'
        required: true
        default: '0.0.1'

jobs:
  build-linux:
    name: Build Linux Native Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '23'
          distribution: 'graalvm'
          native-image: true
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Native Image
        run: |
          ./mvnw package -Pnative
          mv target/*-runner target/native-image-linux-${{ github.event.inputs.version }}

      - name: Upload Artifact (Linux)
        uses: actions/upload-artifact@v3
        with:
          name: native-image-linux-${{ github.event.inputs.version }}
          path: target/native-image-linux-${{ github.event.inputs.version }}
