name: Build Native Image on Windows

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number for the build (e.g., 1.0.0)'
        required: true
        default: '0.0.1'

jobs:
  build-windows:
    name: Build Windows Native Image
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install GraalVM via Chocolatey
        shell: powershell
        run: |
          choco install graalvm
          Write-Output "Running refreshenv..."
          Import-Module "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
          Update-SessionEnvironment
          
          Write-Output "`nListing GraalVM installation directory contents:"
          Get-ChildItem "C:\Program Files\GraalVM" -Recurse | Select-Object FullName
          
          Write-Output "`nLooking specifically for gu.exe:"
          Get-ChildItem "C:\Program Files\GraalVM" -Recurse -Filter "gu.exe" | Select-Object FullName

      - name: Build Native Image
        shell: powershell
        run: |
          Import-Module "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
          Update-SessionEnvironment
          ./mvnw.cmd package -Pnative
          Move-Item target/*-runner.exe "target/native-image-windows-${{ github.event.inputs.version }}.exe"

      - name: Upload Artifact (Windows)
        uses: actions/upload-artifact@v3
        with:
          name: native-image-windows-${{ github.event.inputs.version }}
          path: target/native-image-windows-${{ github.event.inputs.version }}.exe
