name: Build Native Image on Windows

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number for the build (e.g., 1.0.0)'
        required: true
        default: '0.0.1'

jobs:
  build-windows:
    name: Build Windows Native Image
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install GraalVM via Chocolatey
        shell: powershell
        run: |
          # Capture environment before choco install
          Get-ChildItem env: | Sort-Object -Property Name | Out-File env_before_choco.txt
          
          choco install graalvm
          Write-Output "Installed GraalVM..."
          
          # Capture environment after choco but before refreshenv
          Get-ChildItem env: | Sort-Object -Property Name | Out-File env_after_choco.txt
          
          Write-Output "Running refreshenv..."
          Import-Module $env:ChocolateyInstall\helpers\chocolateyProfile.psm1
          
          # Capture environment after refreshenv
          Get-ChildItem env: | Sort-Object -Property Name | Out-File env_after_refresh.txt
          
          # Compare the differences
          Write-Output "Changes made by choco install:"
          Compare-Object (Get-Content env_before_choco.txt) (Get-Content env_after_choco.txt)
          
          Write-Output "`nChanges made by refreshenv:"
          Compare-Object (Get-Content env_after_choco.txt) (Get-Content env_after_refresh.txt)
          
          Write-Output "Installing native-image..."
          gu install native-image

      - name: Build Native Image
        shell: powershell
        run: |
          Import-Module $env:ChocolateyInstall\helpers\chocolateyProfile.psm1
          ./mvnw.cmd package -Pnative
          Move-Item target/*-runner.exe "target/native-image-windows-${{ github.event.inputs.version }}.exe"

      - name: Upload Artifact (Windows)
        uses: actions/upload-artifact@v3
        with:
          name: native-image-windows-${{ github.event.inputs.version }}
          path: target/native-image-windows-${{ github.event.inputs.version }}.exe
