name: Build Native Image on Windows

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number for the build (e.g., 1.0.0)'
        required: true
        default: '0.0.1'

jobs:
  build-windows:
    name: Build Windows Native Image
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install GraalVM via Chocolatey
        run: |
          choco install graalvm # Install GraalVM Java
          Write-Output "Refreshing environment variables..."
          Import-Module "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
          Update-SessionEnvironment # Refresh environment variables in the current session
          gu install native-image # Install the native-image tool

      - name: Build Native Image
        run: |
          ./mvnw.cmd package -Pnative # Build the native image
          rename target\*-runner.exe target\native-image-windows-${{ github.event.inputs.version }}.exe

      - name: Upload Artifact (Windows)
        uses: actions/upload-artifact@v3
        with:
          name: native-image-windows-${{ github.event.inputs.version }}
          path: target/native-image-windows-${{ github.event.inputs.version }}.exe
