name: Build Native Image on Windows

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number for the build (e.g., 1.0.0)'
        required: true
        default: '0.0.1'

jobs:
  build-windows:
    name: Build Windows Native Image
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install GraalVM via Chocolatey
        shell: powershell
        run: |
          choco install graalvm
          Write-Output "Installed GraalVM, refreshing environment..."
          
          # Import and run refreshenv
          Import-Module "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
          Update-SessionEnvironment
          
          # Debug - show all environment variables
          Write-Output "All Environment Variables after refresh:"
          Get-ChildItem env:
          
          # Try to locate GraalVM installation
          Write-Output "Looking for GraalVM in PATH:"
          $env:PATH -split ';' | Where-Object { $_ -like '*GraalVM*' }
          
          Write-Output "JAVA_HOME setting:"
          $env:JAVA_HOME
          
          Write-Output "GRAAL_HOME setting:"
          $env:GRAAL_HOME
          
          # Use whatever path refreshenv set
          Write-Output "Installing native-image using gu from PATH..."
          gu install native-image

      - name: Build Native Image
        shell: powershell
        run: |
          # No need to set paths - use what refreshenv set up
          Write-Output "Building with Maven..."
          ./mvnw.cmd package -Pnative
          
          Write-Output "Renaming output file..."
          Move-Item target/*-runner.exe "target/native-image-windows-${{ github.event.inputs.version }}.exe"

      - name: Upload Artifact (Windows)
        uses: actions/upload-artifact@v3
        with:
          name: native-image-windows-${{ github.event.inputs.version }}
          path: target/native-image-windows-${{ github.event.inputs.version }}.exe
